### PR TITLE
Sync transifex

### PR DESCRIPTION
**Pull request by Gnimuc**

### CODE REVIEW

**Comment by Gnimuc** [comment]
Is it really necessary to build PDF and Julia base on each PR? It looks like Gitlab CI is enough for such a simple sanity check.

**Comment by Roger-luo** [comment]
I think if we don't check pdf in each PR, master branch could break, and then we won't be able to release next version with a pdf.

**Comment by Gnimuc** [comment]
OK, we need to fix the Travis CI timeout error then.

**Comment by Roger-luo** [comment]
@findmyway any idea on this?

**Comment by findmyway** [comment]
I think increasing the waiting minutes a little in the travis config file should address this issue.

<hr>

If the timeout error still exists, we can do something like this here:

https://github.com/JuliaLang/docs.julialang.org/blob/master/pdf/make.jl#L47-L52

**Comment by Roger-luo** [comment]
Looks good to merge.

**Pull request merged**
