### PR TITLE
Fix stdlib

### PR DESCRIPTION
**Pull request by Gnimuc**
It looks like Julia needs a clean env for building stdlib.

### CODE REVIEW

**Comment by Gnimuc** [comment]
It keeps failing on Travis, but everything works fine locally.

**Comment by Roger-luo** [comment]
I'll check this later.

**Comment by Gnimuc** [comment]
```julia
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin17.7.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom
  JULIA_NUM_THREADS = 4
```
I've tested both source-built and binary-installed Julia, so I guess it is Travis that did something sneaky here.

**Comment by Gnimuc** [comment]
build passed in docker: https://hub.docker.com/r/library/julia/tags/

```
root@ad70ecebc069:/JuliaZH.jl# DOCUMENTER_DEBUG=true julia -e 'using Pkg; Pkg.add("Documenter"); include("doc/make.jl")'
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1646k  100 1646k    0     0   397k      0  0:00:04  0:00:04 --:--:--  397k
Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! Unable to get the binding for 'BuildSysImg.build_sysimg'. [src/devdocs/sysimg.md]

ERROR: UndefVarError(:BuildSysImg)

expression ':(BuildSysImg.build_sysimg)' in module 'Main'

Documenter: building cross-references.
 !! Reference for 'Style-Guide' could not be found. [src/manual/variables.md]
 !! Reference for 'The-return-Keyword' could not be found. [src/manual/noteworthy-differences.md]
 !! Reference for 'Composite-Types' could not be found. [src/manual/methods.md]
 !! Reference for 'Profiling' could not be found. [src/manual/performance-tips.md]
 !! Reference for 'Metaprogramming' could not be found. [src/manual/strings.md]
 !! Reference for 'Composite-Types' could not be found. [src/base/base.md]
...
...
...
 !! Invalid local link: unresolved path
    '@ref' in devdocs/object.md
 ?? TRAVIS_REPO_SLUG       = ""
 ??   should match "github.com/JuliaCN/JuliaZH.jl.git" (kwarg: repo)
 ?? TRAVIS_PULL_REQUEST    = ""
 ??   deploying if equal to "false"
 ?? TRAVIS_OS_NAME         = ""
 ??   deploying if equal to "linux" (kwarg: osname)
 ?? TRAVIS_JULIA_VERSION   = ""
 ??   deploying if equal to "1.0" (kwarg: julia)
 ?? TRAVIS_BRANCH          = ""
 ?? TRAVIS_TAG             = ""
 ??   deploying if branch equal to "master" (kwarg: latest) or tag is set
 ?? git commit SHA         = aa47845
 ?? DOCUMENTER_KEY exists  = false
 ?? should_deploy          = false
Documenter: skipping docs deployment.
  You can set DOCUMENTER_DEBUG to "true" in Travis to see more information.
```

**Comment by Roger-luo** [comment]
Let's leave this to 1.1 then, since even with `stdlib` we may not have time to translate that. I guess we should at least tag the package `v1.0.0` before Julia 1.1 released.

**Comment by Gnimuc** [comment]
@Roger-luo  CI passed, good to merge?

**Pull request merged**
